site_name: MeTaSPLoiT
theme: material

docs_dir: "md"
site_dir: "docs"

markdown_extensions:
  - admonition


nav:
    - Home: index.md
    - About: about.md
    - Exemples :
      - Exemple 1: tema1/exemple1.md


extra_css:
  - css/extra.css
